version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis

  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=database
    depends_on:
      - database
      - redis

  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    depends_on:
      - backend

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - database
      - redis
      - backend
      - frontend
