version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis

  frontend:
    build: ./frontend
    ports:
      - 5000:5000

  redis:
    image: redis
